spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: trade-consumer-group # what is this for?
      auto-offset-reset: earliest # do we need this?
app:
  kafka:
    topic: ${KAFKA_TOPIC:my-topic}
    agg-topic: ${KAFKA_AGG_TOPIC:agg-topic}