spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: trade-consumer-group
app:
  kafka:
    topic: ${KAFKA_TOPIC:trade-data-topic}
    aggregation-topic: ${KAFKA_AGG_TOPIC:aggregation-topic}
